spring:
  application:
    name: timesheet-service
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB



server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}



cloud:
  aws:
    credentials:
      access-key: AKIATB4HFZTK3ZEJC6GT
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: timesheetstorage

